### ISSUE TITLE
RestExceptionHandler is not handling InvalidJwtAuthenticationException 

### ISSUE THREAD

**Issue by vineetks** [hantsy/springboot-jwt-sample#2]
When validate token throws this error, we are getting HTML response instead of Error ResponseEntity by RestExceptionHandler

> <!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1></body></html>

**Comment by hantsy** [comment]
@vineetks Can you reproduce the detailed steps?

**Comment by hantsy** [comment]
no response from the reporter.
