### ISSUE TITLE
Where is UserRepository implemented?

### ISSUE THREAD

**Issue by GregJohnStewart** [hantsy/springboot-jwt-sample#3]
`UserRepository` is used several places, but I cannot find where the bean is actually declared or is implemented.

I assume that `AuthenticationManager` picks up the `UserRepository` bean as well and uses it for authentication? Is it possible to not extend `JpaRepository` to create custom repos that are used by the `AuthenticationManager`?

**Comment by hantsy** [comment]
`JpaRepository` is from Spring data project. You can use your now Repository/DAO for the persistence.
