### ISSUE TITLE
Cannot start app.

### ISSUE THREAD

**Issue by emilioyn** [hantsy/springboot-jwt-sample#4]
Hello, I'm trying to run the app but it doesn't boot up, here is the message that comes up:

> 
***************************
APPLICATION FAILED TO START
***************************

Description:

Field jwtProperties in com.example.demo.security.jwt.JwtTokenProvider required a bean of type 'com.example.demo.security.jwt.JwtProperties' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

Action:

Consider defining a bean of type 'com.example.demo.security.jwt.JwtProperties' in your configuration.

**Comment by hantsy** [comment]
Thanks for reporting this issue.
Simply adding a @Configuration on JwtProperties, or @EnableConfigurationProperties on Applicaiton class can enable the ConfigurationProperties
